#!/bin/bash
set -efu

cp mccabe.py test_mccabe.py ${AUTOPKGTEST_TMP}

for py3vers in $(py3versions -s); do
    echo
    echo "***************************"
    echo "*** Testing with ${py3vers}"
    echo "***************************"
    echo
    cd ${AUTOPKGTEST_TMP} && \
        echo -e "Content of current working folder:\n" && \
        ls -la && \
        echo -e "Running tests...\n" && \
        PYTHONPATH=. "${py3vers}" -m pytest -sv test_mccabe.py  && \
        rm -rf .pytest_cache || exit 1
done

echo

exit 0

##!/bin/sh
set -eu

pyvers=$(py3versions -s)

cp -a tests "$AUTOPKGTEST_TMP"
cd "$AUTOPKGTEST_TMP"

export LC_ALL=C.UTF-8
export http_proxy=''

for py in ${pyvers}; do
  echo "-=-=-=-=-=-=-=- running tests for ${py} -=-=-=-=-=-=-=-=-"
  printf '$ %s\n' "${py} -m pytest tests"
  ${py} -m pytest tests
done
